name: coverage
on:
  push:
    branches: [ main ]
  pull_request:
    type: [ opened,reopened,synchronize ]
  workflow_dispatch:

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test --coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 90
          skip-step: install
