name: hello world
on:
  push:
    paths:
      # Không chạy github action khi có sự thay đổi file README.md và toàn bộ file,thư mục trong thư mục docs/
      # (thể hiện bằng dấu chấm than phía trước)
      # Chạy khi các file .js thay đổi (không có dấu chấm than phía trước)
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
    type: [ opened,reopened,synchronize,labeled,unlabeled ]
    paths:
      # Không chạy github action khi có sự thay đổi file README.md và toàn bộ file,thư mục trong thư mục docs/
      # (thể hiện bằng dấu chấm than phía trước)
      # Chạy khi các file .js thay đổi (không có dấu chấm than phía trước)
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: "do bot build"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY