name: secret
on:
  push:
    branches: [ main ]
  pull_request:
    type: [ opened,reopened,synchronize ]
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo This is my secret ${{secrets.DB_PASS}}
      - run : npm install
      - run : |
          API_TOKEN=$(node cli.js rdstr)
          echo THIS IS MY API_TOKEN $API_TOKEN